name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Deploy
        uses: udondan/cdk-nodejs@v0.4.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          SUBDIR: aws-cdk
      - name: Build with Gradle
        run: gradle build
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: build/libs/NexScoreApp-0.0.1-SNAPSHOT.jar   
      - name: Beanstalk Deploy for JAR
        uses: DylanBDev/beanstalk-deploy@initial
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          region: eu-central-1
          application_name: NexScore
          environment_name: Nexscore-env
          version_label: ${{github.SHA}}
          deployment_package: build/libs/NexScoreApp-0.0.1-SNAPSHOT.jar
          use_existing_version_if_available: true
